baseURL = "https://squirrels.wtf/"
languageCode = "en-us"
theme = "whiteplain"
disqusShortname = "bunnymaninfo"

title = "Dear Squirrels, WTF"
description = "Because Life is too Awesome not to share"
copyright = "&copy; Amelia Aronsohn 2012-2019"

footnotereturnlinkcontents = "↩"
ignoreFiles = ["_template.md"]

[params]
  useCDN = false
  showShareIcons = false

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/posts/:year-:month-:day-:title/"

# This is all displayed on author
[params.author]
    name = "Amelia Aronsohn"
    gravatar = "wagthattail@me.com"
    github = "OnlyHaveCans"
    gitlab = "OnlyHaveCans"
    instagram = "OnlyHaveCans"
    keybase = "OnlyHaveCans"
    telegram = "OnlyHaveCans"
    twitter = "OnlyHaveCans"

# Header
[[menu.main]]
  name = "Categories"
  identifier = "categories"
  url = "/categories/"
  weight = 1
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4

# Footer Menu
[[menu.footer]]
  name = "[Exploration #5 Games]"
  identifier = "Exploration #5 Games"
  url = "https://exploration5.games"
  weight = 1
[[menu.footer]]
  name = "[My Gitea]"
  identifier = "Squirrel Gitea"
  url = "https://onlyhavecans.works"
  weight = 2
